### ISSUE TITLE
The declared chant floor (^0.18.32) is lower than the source requires — npm install can produce a repo that does not typecheck

### ISSUE THREAD

**Issue by lex00** [INTENTIUS/behold#108]
`package.json` declares `"@intentius/chant": "^0.18.32"`. On a `0.x` version caret means `>=0.18.32 <0.19.0`, so a plain `npm install` is free to resolve any `0.18.x`. The source does not work on `0.18.x`.

`src/render.test.ts:73` sets `runtimeOwner` on an `IRNode`, which that type gained later. Against `0.18.32`:

```
$ npm run tsc
src/render.test.ts(73,105): error TS2353: Object literal may only specify known
  properties, and 'runtimeOwner' does not exist in type 'IRNode'.
```

It has been invisible because `package-lock.json` pins `0.32.0` and CI runs `npm ci`, which honours the lock. So CI is green and always has been. The declared range is simply not the range the code needs.

**Who this bites.** Anyone who runs `npm install` rather than `npm ci` — a fresh contributor, a dependency bump, a tool that regenerates the lock. They get a typecheck failure in a file they did not touch, with nothing in `package.json` to explain why. I hit exactly this with a stale `node_modules` and spent a while believing `main` was broken.

**Fix.** Raise the declared floor to match what the source actually uses. `^0.32.0` matches the lock and is known good; the true minimum is whichever release introduced `IRNode.runtimeOwner`, which is somewhere between and not worth bisecting for.

**Related, not the same.** `src/component-status.ts` reads `ComponentStatusRow.resources` (#98), which lands in chant 0.34. That one is typed structurally on purpose so an older chant degrades instead of failing to compile — the opposite treatment, because it is an optional widening rather than a hard requirement.

**Comment by lex00** [comment]
Invalid — I misread the manifest. Closing rather than leaving a wrong bug on the tracker.

`package.json` declares `"@intentius/chant": "^0.32.0"`, and has since 1e46b07 ("chore: bump @intentius/* to ^0.32.0"), which predates everything I was working on. The floor is correct and matches both the lockfile and what the source uses.

What actually happened: my local `node_modules` was stale at 0.18.32, never refreshed after that bump. `npm run tsc` failed on `render.test.ts`'s `runtimeOwner`, and I attributed it first to main being broken and then to a declared-floor mismatch. `npm ci` resolves 0.32.0 and the typecheck passes. CI was green throughout, because it runs `npm ci` and was therefore always testing the right thing.

Two wrong conclusions from one stale directory, and neither would have survived a look at `git log -- package.json` — which is what I should have done first.

No change to the repo; the edit I had staged set the value to what it already was.
